[project]
name = "selist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "django>=4.2.23",
    "django-environ>=0.12.0",
    "psycopg2-binary>=2.9.10",
]
