# Generated by Django 5.1.6 on 2025-03-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Finalisation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("accepted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Texte"),
                            ("proposal", "Proposition"),
                            ("finalisation", "Finalisation"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.IntegerField()),
                ("accepted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("offer", "Offre"), ("demand", "Demande")],
                        max_length=6,
                    ),
                ),
            ],
        ),
    ]
