# Generated by Django 5.1.6 on 2025-03-06 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="finalisation",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="chat.proposal"
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="initiator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="initiator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="trade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="chat.trade"
            ),
        ),
    ]
