# Generated by Django 5.1.6 on 2025-03-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("initiation", "Initiation"),
                    ("text", "Texte"),
                    ("proposal", "Proposition"),
                    ("finalisation", "Finalisation"),
                ],
                max_length=12,
            ),
        ),
    ]
