# Generated by Django 5.1.6 on 2025-06-14 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_trade_participants_alter_trade_initiator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="participants",
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[("trade", "Trade"), ("private", "Private")],
                        max_length=10,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="conversations", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trade",
            name="conversation",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trade",
                to="chat.conversation",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="chat.conversation"
            ),
        ),
        migrations.DeleteModel(
            name="PrivateConversation",
        ),
    ]
