# Generated by Django 5.1.6 on 2025-06-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_proposal_refused_proposal_trade_message_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "En cours"),
                    ("finalized", "Finalisé"),
                    ("cancelled", "Annulé"),
                ],
                default="in_progress",
                max_length=11,
            ),
        ),
        migrations.DeleteModel(
            name="Finalisation",
        ),
    ]
